// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"bookstore/services/user/internal/logic"
	"bookstore/services/user/internal/svc"
	"bookstore/services/user/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *user.CreateUserReq) (*user.UserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServiceServer) UpdateUser(ctx context.Context, in *user.UpdateUserReq) (*user.UserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}
